# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0005_verbose_name_plural_for_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.Event')),
                ('lugar', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
            bases=('schedule.event',),
        ),
    ]
