# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_verbose_name_plural_for_calendar'),
        ('Evntes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customevent',
            name='event_ptr',
        ),
        migrations.DeleteModel(
            name='CustomEvent',
        ),
    ]
