# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Evntes', '0002_auto_20171001_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
        ),
    ]
