# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_verbose_name_plural_for_calendar'),
        ('Evntes', '0003_customevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customevent',
            name='id',
        ),
        migrations.AddField(
            model_name='customevent',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, default=12, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.Event'),
            preserve_default=False,
        ),
    ]
