# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_verbose_name_plural_for_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='13.708321, -89.207217', max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='lugar',
            field=models.CharField(default='San Salvador', max_length=255),
            preserve_default=False,
        ),
    ]
