# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 01:24
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20171003_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
