# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 20:12
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20171007_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
