# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_auto_20170927_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='no', max_length=25, unique=True),
        ),
    ]
