# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_auto_20170927_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='no', max_length=25),
        ),
    ]
