# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0005_remove_myuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='aboutme',
            field=models.CharField(default='Hola ', max_length=140),
        ),
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
