# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0006_auto_20170927_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
    ]
