# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0009_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='departament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myauth.Departamento'),
        ),
    ]
