# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20171029_2012'),
        ('myauth', '0011_auto_20171010_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='calendarioUser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Calendar'),
        ),
    ]
